services:
    App\Domain\License\Command\Handler\:
        resource: '%kernel.project_dir%/src/Domain/License/Command/Handler/*Handler.php'
        autowire: true
        tags: [ messenger.message_handler ]

    App\Domain\License\Factory\:
        resource: '%kernel.project_dir%/src/Domain/License/Factory/*Factory.php'
        autowire: true
        public: true

    App\Domain\License\Normalizer\:
        resource: '%kernel.project_dir%/src/Domain/License/Normalizer/*Normalizer.php'
        autowire: true
        public: true

    App\Domain\License\Repository\LicenseRepository:
        class: App\Domain\License\Repository\LicenseRepository
        autowire: true
        public: true
