doctrine:
    dbal:
        schema_filter: /^(?!view_|sessions)/
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            enum: string
        types:
            feed_type: App\Doctrine\Type\FeedType
            license_type: App\Doctrine\Type\LicenseDoctrineType
            license_product: App\Doctrine\Type\LicenseDoctrineProductType
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                dql:
                    datetime_functions:
                        NOW: DoctrineExtensions\Query\Mysql\Now
                mappings:
                    User:
                        mapping: true
                        type: annotation
                        dir: '%kernel.project_dir%/src/Domain/User/Entity'
                        alias: User
                        prefix: 'App\Domain\User\Entity'
                        is_bundle: false
                    EmailVerificationToken:
                        mapping: true
                        type: annotation
                        dir: '%kernel.project_dir%/src/Domain/EmailVerificationToken/Entity'
                        alias: EmailVerificationToken
                        prefix: 'App\Domain\EmailVerificationToken\Entity'
                        is_bundle: false
                    Feed:
                        mapping: true
                        type: annotation
                        dir: '%kernel.project_dir%/src/Domain/Feed/Entity'
                        alias: Feed
                        prefix: 'App\Domain\Feed\Entity'
                        is_bundle: false
                    License:
                        mapping: true
                        type: annotation
                        dir: '%kernel.project_dir%/src/Domain/License/Entity'
                        alias: License
                        prefix: 'App\Domain\License\Entity'
                        is_bundle: false

services:
    App\Doctrine\Type\:
        resource: '../../src/Doctrine/Type/*'
        public: true
