nelmio_api_doc:
    documentation:
        servers:
            -   url: 'http://%api_domain%'
                description: API over HTTP
            -   url: 'https://%api_domain%'
                description: API over HTTPS
        info:
            title: 'Bishop'
            description: This is an awesome app!
            version: 1.0.0
        components:
            schemas:
                tokenInfo:
                    type: object
                    properties:
                        token:
                            type: string
                            example: "Bearer token"
                        refreshToken:
                            type: string
                            example: "refresh_token"
                        tokenExpires:
                            type: string
                            example: "2021-02-11T19:02:52+00:00"
    areas: # to filter documented areas
        default:
            host_patterns:
                - ^api\.
            path_patterns: # an array of regexps
                - ^((?!doc).)*$
            name_patterns:
                - ^(.)*v1(.)*$
            documentation:
                security:
                    - Bearer: [ ]

#nelmio_cors:
#    defaults:
#        allow_credentials: false
#        allow_origin: [ '*' ]
#        allow_headers: [ '*' ]
#        allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
#        max_age: 3600
#        hosts: [ ]
#        origin_regex: false
