nelmio_api_doc:
    documentation:
        servers:
            -   url: 'http://%api_domain%'
                description: API over HTTP
            -   url: 'https://%api_domain%'
                description: API over HTTPS
        info:
            title: 'Bishop'
            description: This is an awesome app!
            version: 1.0.0
        components:
            schemas:
                dateTime:
                    type: datetime
                    example: "2021-02-11T19:02:52+00:00"
                tokenInfo:
                    type: object
                    properties:
                        token:
                            type: string
                            example: "Bearer token"
                        refreshToken:
                            type: string
                            example: "refresh_token"
                        tokenExpires:
                            $ref: '#/components/schemas/dateTime'
                        roles:
                            type: array
                            items:
                                type: string
                feed:
                    type: object
                    properties:
                        id:
                            type: string
                            example: "03f9a882-552c-4fb2-b610-633e5b8bbf96"
                        name:
                            type: string
                            example: "My feed for best market"
                        url:
                            type: string
                            example: "http://bishop.test/xml/client.xml"
                        removedDescription:
                            type: string
                            example: "номер телефона +7 900 ..."
                        stopWords:
                            type: array
                            items:
                                type: string
                            example: ["пистолет", "тик"]
                        addedCity:
                            type: string
                            example: "Екатеринбург"
                        removeLastImage:
                            type: boolean
                            example: true
                        textAfterDescription:
                            type: string
                            example: "куплю гараж +7 999 ..."
                        excludeOutOfStockItems:
                            type: boolean
                            example: true
                        createdAt:
                            $ref: '#/components/schemas/dateTime'
                        updatedAt:
                            $ref: '#/components/schemas/dateTime'
    areas: # to filter documented areas
        default:
            host_patterns:
                - ^api\.
            path_patterns: # an array of regexps
                - ^((?!doc).)*$
            name_patterns:
                - ^(.)*v1(.)*$
            documentation:
                security:
                    - Bearer: [ ]

#nelmio_cors:
#    defaults:
#        allow_credentials: false
#        allow_origin: [ '*' ]
#        allow_headers: [ '*' ]
#        allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
#        max_age: 3600
#        hosts: [ ]
#        origin_regex: false
