parameters:
    http_scheme: '%env(resolve:HTTP_SCHEME)%'
    base_domain: '%env(resolve:BASE_DOMAIN)%'
    web_domain: '%env(resolve:WEB_DOMAIN)%'
    api_domain: '%env(resolve:API_DOMAIN)%'
    support_email: '%env(resolve:SUPPORT_EMAIL)%'
    robot_email: '%env(resolve:ROBOT_EMAIL)%'
