imports:
    - { resource: ../Basic/Config/services.yaml }

services:
    App\Module\Feed\FeedManager:
        class: App\Module\Feed\FeedManager
        autowire: true
        public: true
        arguments:
            $feedManagers:
                - '@App\Module\Feed\Basic\BasicFeedManager'

    App\Module\Feed\FeedChecker:
        class: App\Module\Feed\FeedChecker
        autowire: true
        public: true
