services:
    App\Module\DataTransferObjectFactory\DataTransferObjectFactory:
        class: App\Module\DataTransferObjectFactory\DataTransferObjectFactory
        autowire: true
        public: true
