web:
    resource: '@App/Controller/Web/'
    type: annotation
    host: '%web_domain%'
    schemes: ['%http_scheme%']

api_v1:
    resource: '@App/Controller/Rest/v1/'
    type: annotation
    host: '%api_domain%'
    schemes: ['%http_scheme%']

api_v1_default:
    path: /
    host: '%api_domain%'
    schemes: [ '%http_scheme%' ]
    defaults:  { _controller: App\Controller\Rest\v1\IndexController::index }
