# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

imports:
    - { resource: ../src/Command/Config/config.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory
        public: true

#    Nyholm\Psr7\Factory\Psr17Factory:
#        class: Nyholm\Psr7\Factory\Psr17Factory
#
#    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
#        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
#        public: true
#        arguments:
#            - '@Nyholm\Psr7\Factory\Psr17Factory'
#            - '@Nyholm\Psr7\Factory\Psr17Factory'
#            - '@Nyholm\Psr7\Factory\Psr17Factory'
#            - '@Nyholm\Psr7\Factory\Psr17Factory'
